import { createContext, useContext, useEffect, ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";

export type Brand = {
  name: string;
  tagline: string;
  color: string;
  logoUrl: string | null;
  logoText: string;
  domain: string | null;
  footer: string;
  supportEmail: string | null;
  theme: "light" | "dark" | "auto";
};

const BrandContext = createContext<Brand | null>(null);

const FALLBACK: Brand = {
  name: "BYOR",
  tagline: "Build Your Own Report",
  color: "#0f766e",
  logoUrl: null,
  logoText: "BY",
  domain: null,
  footer: "Generated by BYOR.",
  supportEmail: null,
  theme: "auto",
};

// Convert hex (#rrggbb) to space-separated HSL values for CSS vars.
function hexToHslVar(hex: string): string {
  const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex.trim());
  if (!m) return "172 66% 26%";
  const r = parseInt(m[1], 16) / 255;
  const g = parseInt(m[2], 16) / 255;
  const b = parseInt(m[3], 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = (g - b) / d + (g < b ? 6 : 0); break;
      case g: h = (b - r) / d + 2; break;
      case b: h = (r - g) / d + 4; break;
    }
    h /= 6;
  }
  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

export function BrandProvider({ children }: { children: ReactNode }) {
  const { data } = useQuery<Brand>({
    queryKey: ["/api/brand"],
  });
  const brand = data ?? FALLBACK;

  useEffect(() => {
    const root = document.documentElement;
    const hsl = hexToHslVar(brand.color);
    root.style.setProperty("--brand", hsl);
    root.style.setProperty("--sidebar-primary", hsl);
    document.title = brand.name;
  }, [brand.color, brand.name]);

  return <BrandContext.Provider value={brand}>{children}</BrandContext.Provider>;
}

export function useBrand(): Brand {
  return useContext(BrandContext) ?? FALLBACK;
}
