// Whitelabel brand config. Loaded from env at boot; exposed to the client
// via /api/brand. All fields optional with sensible fallbacks so the app
// runs out-of-the-box, but every deploy can override its identity.

export type Brand = {
  name: string;
  tagline: string;
  color: string;
  logoUrl: string | null;
  logoText: string;
  domain: string | null;
  footer: string;
  supportEmail: string | null;
  theme: "light" | "dark" | "auto";
};

function envOr(key: string, fallback: string): string {
  const v = process.env[key];
  return v && v.trim() ? v.trim() : fallback;
}

function envOrNull(key: string): string | null {
  const v = process.env[key];
  return v && v.trim() ? v.trim() : null;
}

function initialsFrom(name: string): string {
  const parts = name.split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "RF";
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}

export function getBrand(): Brand {
  const name = envOr("BRAND_NAME", "ReportForge");
  const themeRaw = envOr("BRAND_THEME", "auto").toLowerCase();
  const theme: Brand["theme"] =
    themeRaw === "light" || themeRaw === "dark" ? themeRaw : "auto";

  return {
    name,
    tagline: envOr("BRAND_TAGLINE", "Autonomous reporting"),
    color: envOr("BRAND_COLOR", "#0f766e"),
    logoUrl: envOrNull("BRAND_LOGO_URL"),
    logoText: envOr("BRAND_LOGO_TEXT", initialsFrom(name)),
    domain: envOrNull("BRAND_DOMAIN"),
    footer: envOr(
      "BRAND_FOOTER",
      `Generated by ${name}. Reply to this email if you'd like to opt out.`
    ),
    supportEmail: envOrNull("BRAND_SUPPORT_EMAIL"),
    theme,
  };
}
