// Whitelabel brand config. Loaded from env at boot; exposed to the client
// via /api/brand. All fields optional with sensible fallbacks so the app
// runs out-of-the-box, but every deploy can override its identity.

export type Brand = {
  name: string;
  tagline: string;
  color: string;
  logoUrl: string | null;
  logoText: string;
  domain: string | null;
  footer: string;
  supportEmail: string | null;
  theme: "light" | "dark" | "auto";
};

function envOr(key: string, fallback: string): string {
  const v = process.env[key];
  return v && v.trim() ? v.trim() : fallback;
}

function envOrNull(key: string): string | null {
  const v = process.env[key];
  return v && v.trim() ? v.trim() : null;
}

function initialsFrom(name: string): string {
  const parts = name.split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "BY";
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}

// Read order for every field: DB override (app_settings table) → env var → default.
// This lets a tenant who deployed BYOR with one set of env vars rebrand from
// the Settings UI without redeploying. Per-deploy provisioning scripts can
// still set env vars to give each new customer their initial defaults.
function fromDb(key: string): string | null {
  try {
    // Lazy require to avoid a load-order cycle (storage imports secrets imports …)
    const { storage } = require("./storage") as typeof import("./storage");
    const s = storage.getAllSettings();
    return s[key] ?? null;
  } catch {
    return null;
  }
}

function override(envKey: string, dbKey: string, def: string): string {
  const fromOverride = fromDb(dbKey);
  if (fromOverride && fromOverride.trim()) return fromOverride.trim();
  return envOr(envKey, def);
}

function overrideOrNull(envKey: string, dbKey: string): string | null {
  const fromOverride = fromDb(dbKey);
  if (fromOverride && fromOverride.trim()) return fromOverride.trim();
  return envOrNull(envKey);
}

export function getBrand(): Brand {
  const name = override("BRAND_NAME", "brand.name", "BYOR");
  const themeRaw = override("BRAND_THEME", "brand.theme", "auto").toLowerCase();
  const theme: Brand["theme"] =
    themeRaw === "light" || themeRaw === "dark" ? themeRaw : "auto";

  return {
    name,
    tagline: override("BRAND_TAGLINE", "brand.tagline", "Build Your Own Report"),
    color: override("BRAND_COLOR", "brand.color", "#0f766e"),
    logoUrl: overrideOrNull("BRAND_LOGO_URL", "brand.logoUrl"),
    logoText: override("BRAND_LOGO_TEXT", "brand.logoText", initialsFrom(name)),
    domain: overrideOrNull("BRAND_DOMAIN", "brand.domain"),
    footer: override(
      "BRAND_FOOTER",
      "brand.footer",
      `Generated by ${name}. Reply to this email if you'd like to opt out.`
    ),
    supportEmail: overrideOrNull("BRAND_SUPPORT_EMAIL", "brand.supportEmail"),
    theme,
  };
}
